"""Initial schema

Revision ID: f3495c7f2d0f
Revises: 
Create Date: 2026-01-31 12:26:03.004607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3495c7f2d0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=50), nullable=False),
    sa.Column('annual_fee', sa.Integer(), nullable=True),
    sa.Column('account_patterns', sa.Text(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=26), nullable=True),
    sa.Column('updated_at', sa.String(length=26), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_configs_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=26), nullable=True),
    sa.Column('updated_at', sa.String(length=26), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_config_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('parent_category', sa.String(length=100), nullable=True),
    sa.Column('excluded', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('account_mask', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recurring', sa.String(length=50), nullable=True),
    sa.Column('benefit_slug', sa.String(length=50), nullable=True),
    sa.Column('imported_at', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['card_config_id'], ['card_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'name', 'amount', 'account', name='uq_transaction')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('ix_transactions_user_date', ['user_id', 'date'], unique=False)

    op.create_table('user_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_config_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('card_anniversary', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['card_config_id'], ['card_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_config_id', name='uq_user_card')
    )
    op.create_table('benefit_periods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_card_id', sa.String(length=36), nullable=False),
    sa.Column('benefit_slug', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('amount_limit', sa.Float(), nullable=False),
    sa.Column('amount_used', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.String(length=26), nullable=True),
    sa.Column('manual_checked', sa.Integer(), nullable=True),
    sa.Column('manual_amount', sa.Float(), nullable=True),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('reset_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=26), nullable=True),
    sa.Column('updated_at', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_card_id', 'benefit_slug', 'period_start', name='uq_benefit_period')
    )
    with op.batch_alter_table('benefit_periods', schema=None) as batch_op:
        batch_op.create_index('ix_benefit_periods_active', ['user_card_id', 'period_end'], unique=False)

    op.create_table('user_benefit_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_card_id', sa.String(length=36), nullable=False),
    sa.Column('benefit_slug', sa.String(length=50), nullable=False),
    sa.Column('muted', sa.Integer(), nullable=True),
    sa.Column('muted_at', sa.String(length=26), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=26), nullable=True),
    sa.Column('updated_at', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'user_card_id', 'benefit_slug', name='uq_user_benefit_setting')
    )
    with op.batch_alter_table('user_benefit_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_benefit_settings_user_card_id'), ['user_card_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('user_card_id', sa.String(length=36), nullable=True),
    sa.Column('benefit_slug', sa.String(length=50), nullable=True),
    sa.Column('benefit_period_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.String(length=26), nullable=True),
    sa.Column('dismissed', sa.Integer(), nullable=True),
    sa.Column('dismissed_at', sa.String(length=26), nullable=True),
    sa.Column('scheduled_for', sa.String(length=26), nullable=True),
    sa.Column('expires_at', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['benefit_period_id'], ['benefit_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'read'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')
        batch_op.drop_index('ix_notifications_created')

    op.drop_table('notifications')
    with op.batch_alter_table('user_benefit_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_benefit_settings_user_card_id'))

    op.drop_table('user_benefit_settings')
    with op.batch_alter_table('benefit_periods', schema=None) as batch_op:
        batch_op.drop_index('ix_benefit_periods_active')

    op.drop_table('benefit_periods')
    op.drop_table('user_cards')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_date')
        batch_op.drop_index('ix_transactions_category')

    op.drop_table('transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('card_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_configs_slug'))

    op.drop_table('card_configs')
    # ### end Alembic commands ###
